import { colorPalette } from "./chartColors";
import type { CardConfig } from "../config/types";

export const chartConfigs: CardConfig[] = [
  {
    id: "dashboard01",
    type: "chart",
    size: "sm",
    rowSpan: 4,
    csvUrl:
      "https://docs.google.com/spreadsheets/d/e/2PACX-1vQLjue9MJvewUb1ZK7TZ4XgVjM0vRsfb07tPzDTbkGWNzfWAtLfY-NsRHZv5W-HM9W87vorat1fGnz8/pub?gid=1166537229&single=true&output=csv",
    chartType: "bar",
    colors: colorPalette,
    showCardHeader: true,
    showCardHeaderBorder: true,
    showCardActionButton: false,
    showDropdownMenu: false,
    showTotal: false,
    showTrend: false,
    showChartLegend: true,
    legendPosition: "bottom",
    BarChartStacked: true,
    BarChartDirection: "vertical",
    BarChartPercent: false,
    showChartLabelsX: true,
    showChartLabelsY: true,
    showChartGridlineX: false,
    showChartGridlineY: true,
    parserType: "barChart",
  },
  {
    id: "dashboard02",
    type: "chart",
    size: "sm",
    rowSpan: 4,
    csvUrl:
      "https://docs.google.com/spreadsheets/d/e/2PACX-1vQLjue9MJvewUb1ZK7TZ4XgVjM0vRsfb07tPzDTbkGWNzfWAtLfY-NsRHZv5W-HM9W87vorat1fGnz8/pub?gid=1752480555&single=true&output=csv",
    chartType: "bar",
    colors: colorPalette,
    showCardHeader: true,
    showCardHeaderBorder: true,
    showCardActionButton: false,
    showDropdownMenu: false,
    showTotal: false,
    showTrend: false,
    showChartLegend: true,
    legendPosition: "bottom",
    BarChartStacked: true,
    BarChartDirection: "horizontal",
    BarChartPercent: false,
    showChartLabelsX: true,
    showChartLabelsY: true,
    showChartGridlineX: false,
    showChartGridlineY: true,
    parserType: "shareChart",
  },
  {
    id: "dashboard03",
    type: "chart",
    size: "xl",
    rowSpan: 4,
    csvUrl:
      "https://docs.google.com/spreadsheets/d/e/2PACX-1vQLjue9MJvewUb1ZK7TZ4XgVjM0vRsfb07tPzDTbkGWNzfWAtLfY-NsRHZv5W-HM9W87vorat1fGnz8/pub?gid=1716552365&single=true&output=csv",
    chartType: "line",
    colors: colorPalette,
    showCardHeader: true,
    showCardHeaderBorder: true,
    showCardActionButton: true,
    showDropdownMenu: false,
    showTotal: false,
    showTrend: false,
    showChartLegend: true,
    legendPosition: "bottom",
    showChartGridlineX: false,
    showChartGridlineY: true,
    showLineChartGradient: false,
    parserType: "monthlyTimeSeries",
    xAxisType: "time",
    view: "monthly",
  },
  {
    id: "dashboard04",
    type: "chart",
    size: "sm",
    rowSpan: 4,
    csvUrl:
      "https://docs.google.com/spreadsheets/d/e/2PACX-1vQLjue9MJvewUb1ZK7TZ4XgVjM0vRsfb07tPzDTbkGWNzfWAtLfY-NsRHZv5W-HM9W87vorat1fGnz8/pub?gid=935873649&single=true&output=csv",
    chartType: "bar",
    colors: colorPalette,
    showCardHeader: true,
    showCardHeaderBorder: true,
    showCardActionButton: false,
    showDropdownMenu: false,
    showTotal: false,
    showTrend: false,
    showChartLegend: true,
    legendPosition: "bottom",
    BarChartStacked: true,
    BarChartDirection: "horizontal",
    BarChartPercent: false,
    showChartLabelsX: true,
    showChartLabelsY: true,
    showChartGridlineX: false,
    showChartGridlineY: true,
    parserType: "shareChartExtended",
  },
  {
    id: "dashboard05",
    type: "chart",
    size: "sm",
    rowSpan: 4,
    csvUrl:
      "https://docs.google.com/spreadsheets/d/e/2PACX-1vQLjue9MJvewUb1ZK7TZ4XgVjM0vRsfb07tPzDTbkGWNzfWAtLfY-NsRHZv5W-HM9W87vorat1fGnz8/pub?gid=225817772&single=true&output=csv",
    chartType: "pie",
    colors: colorPalette,
    showCardHeader: true,
    showCardHeaderBorder: true,
    showCardActionButton: true,
    showDropdownMenu: false,
    showTotal: false,
    showTrend: false,
    showChartLabelsX: true,
    showChartLabelsY: true,
    showChartLegend: true,
    legendPosition: "bottom",
    pieChartCutout: 20,
    pieChartType: "pie",
    parserType: "pieChart",
  },
  {
    id: "dashboard06",
    type: "chart",
    size: "ssm",
    rowSpan: 4,
    csvUrl:
      "https://docs.google.com/spreadsheets/d/e/2PACX-1vQLjue9MJvewUb1ZK7TZ4XgVjM0vRsfb07tPzDTbkGWNzfWAtLfY-NsRHZv5W-HM9W87vorat1fGnz8/pub?gid=2025299554&single=true&output=csv",
    chartType: "pie",
    colors: colorPalette,
    showCardHeader: true,
    showCardHeaderBorder: true,
    showCardActionButton: true,
    showDropdownMenu: false,
    showTotal: false,
    showTrend: false,
    showChartLabelsX: true,
    showChartLabelsY: true,
    showChartLegend: true,
    legendPosition: "bottom",
    pieChartCutout: 20,
    pieChartType: "pie",
    parserType: "pieChart",
  },
  {
    id: "mapCard",
    type: "map",
    size: "sm",
    rowSpan: 4,
    csvUrl:
      "https://docs.google.com/spreadsheets/d/e/2PACX-1vQLjue9MJvewUb1ZK7TZ4XgVjM0vRsfb07tPzDTbkGWNzfWAtLfY-NsRHZv5W-HM9W87vorat1fGnz8/pub?gid=481175547&single=true&output=csv",
    showCardHeader: true,
    showCardHeaderBorder: true,
    showCardActionButton: false,
    showDropdownMenu: false,
    showTotal: false,
    showTrend: false,
  },
  {
    id: "heatmap01",
    type: "heatmap",
    size: "sm",
    rowSpan: 4,
    csvUrl:
      "https://docs.google.com/spreadsheets/d/e/2PACX-1vQLjue9MJvewUb1ZK7TZ4XgVjM0vRsfb07tPzDTbkGWNzfWAtLfY-NsRHZv5W-HM9W87vorat1fGnz8/pub?gid=1960328559&single=true&output=csv",
    chartType: "heatmap",
    colors: colorPalette,
    showCardHeader: true,
    showCardHeaderBorder: true,
    showCardActionButton: false,
    showDropdownMenu: false,
    showTotal: false,
    showTrend: false,
    showChartLegend: true,
    legendPosition: "bottom",
    parserType: "heatmap",
    xAxisType: "time",
    view: "monthly",
  },
];
