import { getCssVar } from "../utils/cssColorHelper";
import type { CardConfig } from "../config/types";

export const statConfigs: CardConfig[] = [
  {
    id: "stat01",
    type: "stat",
    size: "sm",
    rowSpan: 1,
    csvUrl:
      "https://docs.google.com/spreadsheets/d/e/2PACX-1vQLjue9MJvewUb1ZK7TZ4XgVjM0vRsfb07tPzDTbkGWNzfWAtLfY-NsRHZv5W-HM9W87vorat1fGnz8/pub?gid=854073483&single=true&output=csv",
    chartType: "line",
    colors: [
      getCssVar("--color-teal-600"),
      getCssVar("--color-frost-gray-200"),
    ],
    showCardHeader: true,
    showCardHeaderBorder: false,
    showCardActionButton: false,
    showDropdownMenu: true,
    showTotal: true,
    showTrend: true,
    showChartLabelsX: true,
    showChartLabelsY: true,
    BarChartDirection: undefined,
    BarChartPercent: undefined,
    BarChartStacked: undefined,
    showChartLegend: false,
    legendPosition: "bottom",
    showChartGridlineX: false,
    showChartGridlineY: false,
    showLineChartGradient: true,
    parserType: "monthlyTimeSeriesHardCoded",
    xAxisType: "category",
    view: "monthly",
  },
  {
    id: "stat02",
    type: "stat",
    size: "sm",
    rowSpan: 1,
    csvUrl:
      "https://docs.google.com/spreadsheets/d/e/2PACX-1vQLjue9MJvewUb1ZK7TZ4XgVjM0vRsfb07tPzDTbkGWNzfWAtLfY-NsRHZv5W-HM9W87vorat1fGnz8/pub?gid=139764031&single=true&output=csv",
    chartType: "line",
    colors: [
      getCssVar("--color-teal-600"),
      getCssVar("--color-frost-gray-200"),
    ],
    showCardHeader: true,
    showCardHeaderBorder: false,
    showCardActionButton: false,
    showDropdownMenu: true,
    showTotal: true,
    showTrend: true,
    showChartLabelsX: true,
    showChartLabelsY: true,
    BarChartDirection: undefined,
    BarChartPercent: undefined,
    BarChartStacked: undefined,
    showChartLegend: false,
    legendPosition: "bottom",
    showChartGridlineX: false,
    showChartGridlineY: false,
    showLineChartGradient: true,
    parserType: "monthlyTimeSeriesHardCoded",
    xAxisType: "category",
    view: "monthly",
  },
  {
    id: "stat03",
    type: "stat",
    size: "sm",
    rowSpan: 1,
    csvUrl:
      "https://docs.google.com/spreadsheets/d/e/2PACX-1vQLjue9MJvewUb1ZK7TZ4XgVjM0vRsfb07tPzDTbkGWNzfWAtLfY-NsRHZv5W-HM9W87vorat1fGnz8/pub?gid=470486338&single=true&output=csv",
    chartType: "line",
    colors: [
      getCssVar("--color-teal-600"),
      getCssVar("--color-frost-gray-200"),
    ],
    showCardHeader: true,
    showCardHeaderBorder: false,
    showCardActionButton: false,
    showDropdownMenu: true,
    showTotal: true,
    showTrend: true,
    showChartLabelsX: true,
    showChartLabelsY: true,
    BarChartDirection: undefined,
    BarChartPercent: undefined,
    BarChartStacked: undefined,
    showChartLegend: false,
    legendPosition: "bottom",
    showChartGridlineX: false,
    showChartGridlineY: false,
    showLineChartGradient: true,
    parserType: "monthlyTimeSeriesHardCoded",
    xAxisType: "category",
    view: "monthly",
  },
];
