import { getCssVar } from "../utils/cssColorHelper";
import { colorPalette } from "./chartColors";
import type { CardConfig } from "../config/types";

export const widgetConfigs: CardConfig[] = [
  {
    id: "widget01",
    type: "widget",
    size: "xs",
    rowSpan: 1,
    csvUrl:
      "https://docs.google.com/spreadsheets/d/e/2PACX-1vQLjue9MJvewUb1ZK7TZ4XgVjM0vRsfb07tPzDTbkGWNzfWAtLfY-NsRHZv5W-HM9W87vorat1fGnz8/pub?gid=1403129334&single=true&output=csv",
    chartType: "bar",
    colors: [
      getCssVar("--color-teal-600"),
      getCssVar("--color-frost-gray-200"),
    ],
    showCardHeader: true,
    showCardHeaderBorder: false,
    showCardActionButton: false,
    showDropdownMenu: false,
    showTotal: false,
    showTrend: true,
    BarChartDirection: "vertical",
    BarChartPercent: false,
    BarChartStacked: false,
    showChartLabelsX: true,
    showChartLabelsY: false,
    showChartLegend: false,
    legendPosition: "bottom",
    showChartGridlineX: false,
    showChartGridlineY: false,
    showLineChartGradient: false,
    showWidgetSubtitle: true,
    parserType: "widgetChart",
  },
  {
    id: "widget02",
    type: "widget",
    size: "xs",
    rowSpan: 1,
    csvUrl:
      "https://docs.google.com/spreadsheets/d/e/2PACX-1vQLjue9MJvewUb1ZK7TZ4XgVjM0vRsfb07tPzDTbkGWNzfWAtLfY-NsRHZv5W-HM9W87vorat1fGnz8/pub?gid=1129371862&single=true&output=csv",
    chartType: "pie",
    colors: colorPalette,
    showCardHeader: true,
    showCardHeaderBorder: false,
    showCardActionButton: false,
    showDropdownMenu: false,
    showTotal: false,
    showTrend: false,
    showChartLabelsX: true,
    showChartLabelsY: true,
    showChartLegend: true,
    legendPosition: "right",
    showChartGridlineX: false,
    showChartGridlineY: false,
    showLineChartGradient: false,
    pieChartCutout: 10,
    pieChartType: "pie",
    showWidgetSubtitle: false,
    parserType: "pieChart",
  },
  {
    id: "widget03",
    type: "widget",
    size: "xs",
    rowSpan: 1,
    csvUrl:
      "https://docs.google.com/spreadsheets/d/e/2PACX-1vQLjue9MJvewUb1ZK7TZ4XgVjM0vRsfb07tPzDTbkGWNzfWAtLfY-NsRHZv5W-HM9W87vorat1fGnz8/pub?gid=263914883&single=true&output=csv",
    chartType: "bar",
    colors: [
      getCssVar("--color-teal-600"),
      getCssVar("--color-frost-gray-200"),
    ],
    showCardHeader: true,
    showCardHeaderBorder: false,
    showCardActionButton: false,
    showDropdownMenu: false,
    showTotal: false,
    showTrend: true,
    BarChartDirection: "vertical",
    BarChartPercent: false,
    BarChartStacked: false,
    showChartLabelsX: true,
    showChartLabelsY: false,
    showChartLegend: false,
    legendPosition: "bottom",
    showChartGridlineX: false,
    showChartGridlineY: false,
    showLineChartGradient: false,
    showWidgetSubtitle: true,
    parserType: "widgetChart",
  },
  {
    id: "widget04",
    type: "widgetMap",
    size: "xs",
    rowSpan: 1,
    csvUrl:
      "https://docs.google.com/spreadsheets/d/e/2PACX-1vQLjue9MJvewUb1ZK7TZ4XgVjM0vRsfb07tPzDTbkGWNzfWAtLfY-NsRHZv5W-HM9W87vorat1fGnz8/pub?gid=796109113&single=true&output=csv",
    showCardHeader: true,
    showCardHeaderBorder: false,
    showCardActionButton: false,
    showDropdownMenu: false,
    showTotal: false,
    showTrend: false,
    showWidgetSubtitle: true,
    parserType: "widgetChart",
  },
];
